x-mautic-volumes:
  &mautic-volumes
  - /portainer/${COMPOSE_PROJECT_NAME}-mautic/config:/var/www/html/config:z
  - /portainer/${COMPOSE_PROJECT_NAME}-mautic/logs:/var/www/html/var/logs:z
  - /portainer/${COMPOSE_PROJECT_NAME}-mautic/media/files:/var/www/html/docroot/media/files:z
  - /portainer/${COMPOSE_PROJECT_NAME}-mautic/media/images:/var/www/html/docroot/media/images:z
  - /portainer/${COMPOSE_PROJECT_NAME}-cron:/opt/mautic/cron:z
services:
  # Database moved to separate stack - see percona/docker-compose.percona.yml
  # Start with: cd percona && docker-compose -f docker-compose.percona.yml up -d

  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes: 
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - default

  mautic_web:
    image: mautic/mautic:6.0.7-apache
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
    env_file:
      - .mautic_env
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    networks:
      - default
      - web
      - mautic-db-network
    external_links:
      - percona-db:mysql
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      
      # HTTP Router - redirects to HTTPS
      - "traefik.http.routers.mautic-http.rule=Host(`newsletter.smartoys.be`)"
      - "traefik.http.routers.mautic-http.entrypoints=http"
      - "traefik.http.routers.mautic-http.middlewares=https-redirect"
      
      # HTTPS Router
      - "traefik.http.routers.mautic-https.rule=Host(`newsletter.smartoys.be`)"
      - "traefik.http.routers.mautic-https.entrypoints=https"
      - "traefik.http.routers.mautic-https.tls=true"
      - "traefik.http.routers.mautic-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.mautic-https.middlewares=secure-headers"
      
      # Service - specify the port
      - "traefik.http.services.mautic.loadbalancer.server.port=80"
      
      # Connect to the web network
      - "traefik.docker.network=web"

  mautic_cron:
    image: mautic/mautic:6.0.7-apache
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
    env_file:
      - .mautic_env
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default
      - mautic-db-network
    external_links:
      - percona-db:mysql

  mautic_worker:
    image: mautic/mautic:6.0.7-apache
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
    env_file:
      - .mautic_env
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default
      - mautic-db-network
    external_links:
      - percona-db:mysql

volumes:
  rabbitmq-data:

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-docker
  web:
    external: true
  mautic-db-network:
    external: true
    name: mautic-db-network